# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (1)
# #########################################################################

class YugiohCard(BaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    stars: typing.Optional[int] = None
    ATK: typing.Optional[int] = None
    DEF: typing.Optional[int] = None
    description: typing.Optional[str] = None
    card_number: typing.Optional[str] = None
    video_game_identifier: typing.Optional[int] = None
    edition: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
